### ISSUE TITLE
Stratux v1.4r5 not passing GPS info to iFly 10.2.75

### ISSUE THREAD

**Issue by bazimm41** [cyoung/stratux#710] opened 2018-04-23 16:21 UTC
1. Stratux version: v1.4r5
2. Stratux config:

    SDR
      - [ ] single
      - [x] dual

    GPS
      - [x] yes
      - [ ] no
      type:

    AHRS
      - [x] yes
      - [ ] no

    power source: ship power via lighter adapter

    usb cable: Anker

3. EFB app and version: (e.g., WingX Pro7 8.6.2) iFly 10.2.75

    EFB platform: (e.g., iOS 9.2) Android 

    EFB hardware: (e.g., iPad Mini 2) Asus ZenPad

4. Description of your issue:

I tried to update from 1.4r4 to this release via the .sh package. It didn't take, so I downloaded the entire package and flashed the sd card. Everything seems to work as far as the Stratux webpage goes but it is not passing gps position to iFly 10.2.75. UAT and 1090ES traffic is being passed to iFly as per usual.

If possible, enable "Replay Logs", reproduce the problem, and provide a copy of the logs in http://192.168.10.1/logs/stratux/ and http://192.168.10.1/logs/stratux.log.

**Comment by Ergonomicmike** [comment] 2018-04-26 00:59
I haven't been able to test this yet. (I forgot to bring a battery with me for the Stratux last week when I flew for the first time in a month.) But 1) I'm asking another iFly'er if he's seen this and 2) we plan to fly this Friday. 

I've already updated my tablets to iFly 10.2.75. So I'll leave the Stratux alone on the flight out. If that works, then I'll try sh'ing the Stratux up on the flight back.

 I'll plan to report after that.

**Comment by bazimm41** [comment] 2018-04-26 17:00
Thank you. When next I go flying I'll try to do the "Replay Logs" and provide copies here. It may be a bit before I can get to it though.

**Comment by Ergonomicmike** [comment] 2018-04-28 00:36
Okay, as I said in Slack and in the iFly forum, I have confirmed that iFly 10.2.75 does not receive GPS info from Stratux 1.4r5.

I flew DVT to INW (and back) today with a recent sh'd version of Stratux 1.4r4 and iFly 10.2.75. (915391fa91) Everything worked.

Then, at INW, I changed out the microSD card in the Straux and put in a new one with a fresh image of Stratux 1.4r5. When I powered it up, I heard iFly "bing" (indicating a connection with the Stratux), and indeed, I was getting a heart beat and ADS-B data. But no GPS data.

I rebooted the Stratux and iFly. No change. I turned the slider for GPS off/on in the Stratux. No change. The Stratux UI shows satellites and the GPS webpage showed my positing. Apparently it's not getting to iFly.

I say that because I had ADS-B logging on in iFly for both trips and the log on the way up (when iFly was getting GPS data from Stratux) is about twice as large as the log file on the way home.

I have uploaded the stratux replay log from v1.4r5 (the trip home) here. http://jmp.sh/ofGZ6Wj  (An sqlite file right?)

I'm sending the two iFly logs to iFly - although I'll be surprised if he can tell me anything except "I'm not getting GPS data.

FWIW, I haven't run replay logs in a long time. But I got the old message we used to see.

![sqlite errors](https://user-images.githubusercontent.com/15025888/39389834-08e35f5e-4a7c-11e8-872c-f1c62890cd18.jpg)

**Comment by walterboyd2** [comment] 2018-04-30 16:55
This is Walter from iFly GPS.  I've confirmed this issue.  This is the problem is byte 3 from the GDL90 Status message (message id 0x65).  According to my spec, a value here of "1" (ascii 49) = non-WAAS fix, "2" (ascii 50) = WAAS fix, anything else is no fix.  We're getting a value of "#" (ascii 35) for this byte.  

Any thoughts on what this means?  Or is it a bug?

**Comment by Ergonomicmike** [comment] 2018-04-30 18:02
Thanks for chiming in, Walter. I'm sure Chris will ask what he needs to know to fix this. But out of curiosity, when you say "random values," does that mean that the byte toggles randomly between 1 and 2? Or that the values are random ascii?

**Comment by walterboyd2** [comment] 2018-04-30 18:09
They jump around all over the place.  But I've figured out that 0x65 is not a standard GDL90 message.  I think this was a proprietary message type that started with the Radenna SkyRadar, and Stratux is probably using it for something totally different.  When I ignore this message, it works - so I'll make this change in our code for release in 10.3.  

I'd still like to know what Stratux is doing with this message.

On a different note, the ADSB recording I'm playing with is not receiving any weather data, just GPS, Traffic, and AHRS.  The UplinkData message is missing entirely.

**Comment by cyoung** [comment] 2018-04-30 18:42
@walterboyd2 - makes sense. 0x65 is the ForeFlight "ID message":

https://github.com/cyoung/stratux/blob/ddbd3d5ef8f0f8b967c9f96450f3e432ea5b006c/main/gen_gdl90.go#L646-L677

https://www.foreflight.com/connect/spec/

**Comment by cyoung** [comment] 2018-04-30 18:45
I couldn't find anywhere that 0x65 is defined a GDL90 "status message"? Did ForeFlight choose their message ID number poorly?

**Comment by walterboyd2** [comment] 2018-04-30 18:59
FYI, I checked a log file from Ergonomicmike and there is weather data.  So my earlier reported issue about missing UplinkData must be just my box.

**Comment by bazimm41** [comment] 2018-04-30 19:52
Thank you Mike and Walter for working to resolve this issue. And good job iFly community to get a fix in the works so quickly.

**Comment by Ergonomicmike** [comment] 2018-05-05 02:28
Sad to report that the latest iFly fix did not work for me today with Stratux 1.4r5. (FWIW, my Stratux has the AHRS board in it. (In case yet another FF message for AHRS is messing something up in iFly.) Had to revert to v1.4r4.

**Comment by Ergonomicmike** [comment] 2018-05-06 04:27
I re-imaged the sdcard and expanded the file system. Stratux is working again. IFly still is NOT getting GPS data. I get about 5 seconds of GPS to iFly,and then nothing for about a minute. Then the cycle repeats.

I captured some iFly logs for Walter and will send.

**Comment by bazimm41** [comment] 2018-05-06 06:29
Thank you for keeping up on this. Weather has been complete crud here for the last couple of weeks and I haven't been up since this whole thing started. Hopefully next week.

**Comment by Ergonomicmike** [comment] 2018-05-07 18:45
Turns out that, even tho the "read me" for the last iFly beta release said that the fix for this issue was in, the fix did not get implemented. Should be okay when the next beta is released. (Hopefully this week.)

**Comment by Ergonomicmike** [comment] 2018-05-13 04:58
I flew with iFly 10.3.3 and Stratux v1.4r5. They fixed the GPS problem. So @bazimm41 can close this issue.

**Closed** 2018-05-16 20:51 UTC
