### ISSUE TITLE
Faux tail numbers of "N" and "00000000" with new dump1090

### ISSUE THREAD

**Issue by Ergonomicmike** [cyoung/stratux#298] opened 2016-03-01 00:10 UTC
1. Stratux version: 0.7b3 + 855b "alpha"
2. Stratux config: dual SDR, GPS yes (BU-353), AHRS no; battery, battery cable: Anker E5, Anker cable.
3. EFB app and version (iFly v9.4 RC2). EFB platform (Android KK). EFB hardware (Azus Zenad S 8).
4. Description of your issue. 

I noticed two goofy tail numbers today. "N" and "00000000." (Eight zeros.) Here's the screen shot:
http://postimg.org/image/yx922cu5j/

And here's a clip from es.log
```

{"Icao_addr":11097569,"DF":20,"CA":0,"TypeCode":19,"SubtypeCode":1,"SBS_MsgType":5,"SignalLevel":0.001005,"Tail":"00000000","Squawk":null,"Emitter_category":null,"OnGround":false,"Lat":null,"Lng":null,"Position_valid":false,"NACp":null,"Alt":41000,"AltIsGNSS":false,"GnssDiffFromBaroAlt":null,"Vvel":null,"Speed_valid":false,"Speed":null,"Track":null,"Timestamp":"2016-02-29T17:54:05.797Z"}
49016938747301,
```

**Comment by Nokomis449** [comment] 2016-03-01 00:24
Both of those "tail numbers" show up in a flightaware search with local and international flights between Europe & the Amaricas, so it's not a bug that's limited to Stratux although it could be a dump1090 bug.  But it's most likely some of your aforementioned chemtrail conspiracy aircraft flown by martians for the Jade Helm exercises.  I'm keeping my tinfoil hat handy just in case.

**Comment by Ergonomicmike** [comment] 2016-03-01 00:42
Interesting. I wonder how they display at ATC? (peepsnet? Or do we have to have Clearances for you to tell us?) 

If this issue isn't unique to Stratux but an "up the chain" problem, should I close this issue then? It's not like a bizarre call sign is a deal breaker.

**Comment by peepsnet** [comment] 2016-03-01 00:47
We do not care at all about your ADS-B!!! 
Our displays do not look at adsb data. We associate your squawk code to flight info.

That could be just miscondigured ADS-B eqp. I would like to also see the ICAO HEX code for the targets at the same time. I know you could grep log files but is can be easier then that. 

Ill add another column to the traffic page for that datdata or if @avsquirrel could get that. I know he now has it share with the callsign until the callsign is known but it seems like too many times I need the hex code along with the callsign

**Comment by cyoung** [comment] 2016-03-01 00:53
Could you post the nnnn-es.log(.gz) and nnnn-dump1090.log(.gz)?

**Comment by cyoung** [comment] 2016-03-01 00:58
Tail number was N700PP, btw.

**Comment by Ergonomicmike** [comment] 2016-03-01 01:27
https://www.sendspace.com/file/mfo8b8

**Comment by cyoung** [comment] 2016-03-01 05:21
Here's one example:

```
*8dc02d2122c30c30c30c30deacc6;
CRC: 000000
RSSI: -26.3 dBFS
Score: 1800
Time: 1644796131.00us (phase: 0)
DF 17: ADS-B message.
Capability     : 5 (Level 2+, airborne)
ICAO Address   : c02d21
Extended Squitter  Type: 4
Extended Squitter  Sub : 2
Extended Squitter  Name: Aircraft Identification and Category
Aircraft Type  : A2
Identification : 00000000
```

c02d21 has Canadian registration C-FRCI.


And another one:

```
*a0001a3020c30c30c30c300f2c91;
CRC: a955e1
49016889971363,RSSI: -30.0 dBFS
Score: 1000
Time: 670358238.42us (phase: 300)
DF 20: Comm-B, Altitude Reply.
Flight Status  : Normal, Airborne
DR             : 0
UM             : 0
Altitude       : 41000 feet
ICAO Address   : a955e1
BDS 2,0 Aircraft Identification : 00000000
```

a955e1 has tail number N700PP.


Both C-FRCI and N700PP are blocked on FlightAware.

If it was done intentionally and is just a privacy thing, then I question why this hasn't come up before.

**Comment by Ergonomicmike** [comment] 2016-03-01 05:42
Street address: Military Trail, Jupiter, FL. (Peepsnet's backyard.) http://registry.faa.gov/aircraftinquiry/NNum_Results.aspx?NNumbertxt=700pp

Before that, Arlington, VA. 

CIA?

**Comment by bkwny** [comment] 2016-03-01 10:55
I am not yet convinced Stratus correctly decoded what was sent.  I too yesterday saw an aircraft with N and one with 00000000.  And I have never seen one before.  And I am on the other side of the country from ErgonomicMike.  I suggest we leave this open for a while and keep our eyes open.

**Comment by Ergonomicmike** [comment] 2016-03-01 13:40
Seems like the only definitive way to see if this issue is a function of the new dump1090 is to have two Stratuxi running side by side, one with this alpha and the other with v0.7b3 or below to compare to. (Or have a production ADS-B unit to compare to, which we presume does everything right.) I don't have either for testing. And I don't have any old logs to grep thru.

Since the two aircraft were blocked by FlightAware, I lean to thinking that the Identifications were intentionally obscured. I mean, it's not like we're getting garbage in the field. As to why we haven't noticed them before - in addition to hit or miss (I mean, how often do we look at the Traffic page?), SuperTuesday campaigning? (It's amazing that bkwny & I saw the same call signs. Would be interesting to know if his logs show they're the same aircraft.)

**Comment by cyoung** [comment] 2016-03-01 13:50
@bkwny - do you have a copy of *es.log and *dump1090.log?

@Ergonomicmike - Same "call signs" = "00000000"? There are two different aircraft in your logs alone that have that "call sign".

**Comment by Nokomis449** [comment] 2016-03-01 13:51
When I watch the traffic on my PiAware at home, it is not uncommon to see nonsensical tail numbers. All ???????,12345 excetera. I believe you are correct, FlightAware is blocking the tail numbers as required and this is a non-issue for Stratux.

**Comment by cyoung** [comment] 2016-03-01 13:58
If anyone wants to investigate this, try taking a look at `*8dc02d2122c30c30c30c30deacc6;` and seeing how dump1090-antirez and dump1090-MalcolmRobb would have decoded it. We could probably filter out some junk, but I'd like to know what has changed since moving to this new version of dump1090.

**Comment by 224XS** [comment] 2016-03-01 14:09
N700PP is a G-IV registered to a leasing corporation based in a strip mall storefront on a commercial street near Palm Beach, FL (I have relatives in the area)

**Comment by skypuppy** [comment] 2016-03-01 14:34
IIRC, one of the vendors of ads-b in/out units, one a unit designed for 
experimentals, allows you to set your id as "0" so that your real id 
won't be known to whomever is watching (including FAA) and to be able to 
fly until your "official ID" is assigned.

**Comment by AvSquirrel** [comment] 2016-03-01 14:34
@cyoung : Hand-decoding of `*8dc02d2122c30c30c30c30deacc6;` checks out to all zeros.
````
8dc02d2122c30c30c30c30deacc6
Byte 1 is  downlink format and capability.
8d --> 10001 101 -> DF = 17, CA = 5

Bytes 2-4 are the ICAO 24-bit code.
c0 2d 21 -> ICAO C02D21

Byte 5 is the type code and emitter category.
22  -> 00100 010 -- > TC4 = Set "A", emitter category 2

Bytes 6-11 encode the callsign in a 6-bit format.
c3 0c 30 c3 0c 30 -->
1100 0011 0000 1100 0011 0000 1100 0011 0000 1100 0011 0000 -->
110000 110000 110000 110000 110000 110000 110000 110000
110000 ==  zero

Bytes 12-14 are a checksum.
de ac c6 --> Checksum
````

**Comment by Ergonomicmike** [comment] 2016-03-01 14:43
@cyoung Regarding the "same" call signs, I was referring to "00000000” and "N."Bwkny says he saw both too. If you look at the screen shot of my Traffic page, they were both flying at the same time. So if you find 00000000 at 19:23Z, there should be an "N" call sign aircraft nearby too.

@224XS "How to make a million dollars." Open a Leasing Corp in a strip mall. (I think 60 Minutes did a story on fake front govt ops like this a couple years ago.)

**Comment by AvSquirrel** [comment] 2016-03-01 14:48
"N       " appears to be A4AB66, N40ML, an EMB-505 registered to a dealer in Fort Lauderdale.

**Comment by 224XS** [comment] 2016-03-01 14:49
Cmon now Mike, you know that, in aviation, to make a million dollars in aviation, you start with 2 million!
Three million would be better.

**Comment by Axtel4** [comment] 2016-03-01 15:39
Just a comment about the xxxx-se.log.  Could the ICAO address be stored as Hex again?  It is really strange looking at it as a decimal value.

Also, instead of including "Tag": Value for each entry can a header row be added when the file is created then the values would be appended below the header.  This will save from writing redundant data to the file each time a line is written.  It would also make it easier to parse the data for analysis with ready made headers in the file.

Thanks.

**Comment by Ergonomicmike** [comment] 2016-03-01 15:43
I'm not doubting that Jeff saw "????????" as a Call Sign. But I am surprised that question marks are in the allowed character set for ADS-B stuff.

**Comment by peepsnet** [comment] 2016-03-01 15:45
Guys, 
Why can this not just some ppl who entered garb-d-gook in the FMS. If i remember to boot up my stratux ill pull the log. ]

This jetblue entered BWIFATTY in his FMS as flight number and it showed up on my stratux

I know that in an advanced FMS the pilot enters the flight number(SWA143) but the N-number is harder to get to and change(N13245) so the pilot just entered a flight number as 0000000000 or N.

Most of the SWA gues and ASY seem to only use their number(i.e. 143 for SWA143) so you see 143 or 2425 not SWA2425 in the traffic screen

**Comment by peepsnet** [comment] 2016-03-01 17:52
> 9494704596657,Flight Status  : Normal, Airborne
9494704636345,DR             : 0
9494704677907,UM             : 0
9494704719574,Altitude       : -200 feet
9494704759730,ICAO Address   : a21f94
9494704801449,BDS 2,0 Aircraft Identification : BWIFATTY
9494707367074,*8ca81b2a38ffd183b79b77098a46;
9494707433011,CRC: 000000
9494707474730,RSSI: -3.3 dBFS
9494707513636,Score: 1800
9494707551865,Time: 6180035245.67us (phase: 120)

**Comment by Nokomis449** [comment] 2016-03-01 18:06
![snipimage](https://cloud.githubusercontent.com/assets/15808621/13436632/dc0df450-dfa5-11e5-85bc-850973d1cae2.JPG)

As luck would have it, "????????" just flew over.

**Comment by Nokomis449** [comment] 2016-03-01 19:41
Here comes another Mr ?????? along with Mr All Zero's and a fella with a space in his number.
![snipimage](https://cloud.githubusercontent.com/assets/15808621/13439436/3aafae38-dfb3-11e5-8176-17040f3fa709.JPG)

**Comment by bkwny** [comment] 2016-03-01 21:25
@cyoung - /var/log/*es.log?  And where is *dump1090.log?

**Comment by AvSquirrel** [comment] 2016-03-01 21:40
@peepsnet:
> Why can this not just some ppl who entered garb-d-gook in the FMS

Agreed. Even GA Mode S transponders can be set up to allow callsign entry (it's a config menu option that takes about 15 seconds to set), and any alphanumeric string of up to eight characters is a valid input. GTX330 pilot's guide:

![image](https://cloud.githubusercontent.com/assets/14127245/13442575/9130988a-dfc2-11e5-91b8-f8c4315b2ac1.png)

From what I've seen so far, there's nothing to be solved on our end. It's all either lazy data entry ("1304"), guys messing around ("BWIFATTY"), or superficial attempts to hide a flight number ("00000000")

BTW, I saw your request for adding a ICAO codes to UI. Web design really isn't my forte, but I'll see what I can do. The UI's getting a bit crowded, so maybe a toggle to switch between callsign and ICAO? Thinking of doing something similar for my distance / bearing display, to toggle between lat/lon and distance.

@Ergonomicmike:
>  But I am surprised that question marks are in the allowed character set for ADS-B stuff.

They're not. The ES specification calls for a "6-bit subset of the International Alphabet Number 5 (IA-5)" . Valid characters are A-Z, [space], and 0-9.

![image](https://cloud.githubusercontent.com/assets/14127245/13441405/8f94709c-dfbc-11e5-9659-50b308a6dc6f.png)

These map out to decimal values 1-26, 32, and 48-57 in the raw message. Older versions of dump1090 (antirez, MalcolmRobb) substituted question marks for any invalid values; dump1090-mutability does its lookup against a more complete character set (i.e. the gaps are filled with the unused ASCII characters that correspond to those values). Either way, a question mark tells you that something is wrong with the value that was sent / decoded.

The callsigns that decoded as "00000000" or "N______" or "4237 94" were intentionally set that way. The raw ES messages for "00000000" don't contain a run of zeroes; they contained eight consecutive '48' values (or 0x30 hex) packed together into six bytes -- the `c3 0c 30 c3 0c 30`  noted earlier. Likewise, you're not going to "accidentally" see seven consecutive spaces (0x20)

**Comment by Ergonomicmike** [comment] 2016-03-01 21:51
Thanks for the answer on the question marks. Didn't make sense that they would be allowed during entry. But it makes sense that they're being added during decode.

I agree with you that these are intentional goofy ADS-B id's and there's nothing we can do about it. But I'll leave it to Chris to close this issue.

**Comment by cyoung** [comment] 2016-03-01 22:04
@bkwny - Check /var/log/stratux/.

@AvSquirrel - any idea why this didn't show up before? Well, maybe it did - but I certainly never saw it before this version switch. Say, are there standard formats we could regex for and only accept for tail numbers, flight numbers, etc? Filtering out garbage identifiers would be ideal.

**Comment by Ergonomicmike** [comment] 2016-03-01 22:10
@Nokomis449 Do you still have that production box that you used to confirm the "Papa Alpha" zero altitude issue? How does it report these strange tail numbers?

**Comment by bkwny** [comment] 2016-03-01 22:21
@cyoung - I would suggest not masking off data.  Just print whatever the aircraft is broadcasting and document that's what you're doing.

**Comment by AvSquirrel** [comment] 2016-03-01 22:23
Odd callsigns captured with dump1090-MalcolmRobb (data collected 1/1/2016) include "TEST1234", "7", "H ????AA", and "????????"
````

27228248459619,MSG,6,111,11111,A3C9B4,111111,2016/01/01,15:14:17.475,2016/01/01,15:14:17.465,H ????AA,,,,,,,3620,-1,0,0,0
27251844096121,MSG,6,111,11111,A3C9B4,111111,2016/01/01,15:14:41.094,2016/01/01,15:14:41.061,H ????AA,,,,,,,3620,0,0,0,0
26996912077765,MSG,1,111,11111,A52E54,111111,2016/01/01,15:10:26.182,2016/01/01,15:10:26.128,7       ,,,,,,,,,,,0
8962961519799,MSG,1,111,11111,ADF992,111111,2016/01/01,17:46:33.462,2016/01/01,17:46:33.456,TEST1234,,,,,,,,,,,
8974828194065,MSG,5,111,11111,AC8B43,111111,2016/01/01,17:46:45.369,2016/01/01,17:46:45.323,????????,1525,,,,,,,0,,0,0

**Comment by Nokomis449** [comment] 2016-03-01 22:24
Not sure which box that was (SkyRadar DX?), but I keep the Stratux's updated to the bleeding edge.  I'll be flying about 10 hours this weekend with both so I'll look for "0" altitudes.  If anybody in Florida sees N6776N flying around, waggle your wings at me.

**Comment by AvSquirrel** [comment] 2016-03-01 22:25
@cyoung -- You could make a case that any callsign that contains invalid characters (i.e. not A-Z, [space], 0-9) should be rejected. I wouldn't touch any of the other "odd" formats if they checksum and decode correctly.

**Comment by Axtel4** [comment] 2016-03-01 22:31
Well at least Stratux is letting more people to pay attention to the data that's floating around out there.  There are even instances where installations are sending the wrong Mode S address for their tail number, and this is not the anonymous address.

**Comment by Ergonomicmike** [comment] 2016-03-01 22:40
@Nokomis449 Oops - my mistake. Confused with ScraboTower near me. NM. (But if you have a SkyRader with you while you're flying, see if you can see any goofy Call Signs on it.)

**Comment by bkwny** [comment] 2016-03-01 22:45
@cyoung - Per your request:  
https://drive.google.com/file/d/0B99rMHH_dTvASzZQUnlvZ2FYRFU/view?usp=sharing

**Comment by bkwny** [comment] 2016-03-01 22:47
@Axtel4 - That wrong Mode S really, really bothers me.  It doesn't have to be a mistake.  It can be done on purpose.  There is no way for me to prohibit somebody else from transmitting my Mode S code.  Arggh...

**Comment by Axtel4** [comment] 2016-03-01 23:05
@bkwny 

It happens for a number of reasons: the N number is changed but the Mode S address isn't, a hardware failure in the transponder, mis-programming / incorrect strapping at installation, intentionally changed, etc.

People complain about the FAA requiring the correct data out to get data in, but that is one method that is being used to validate the systems in operation.  If someone isn't getting In when they think they should, it will force them to verify their installation is correct.  We should see less of the wrong ICAO addresses as we get closer to the mandate and the systems are being validated.

**Comment by Nokomis449** [comment] 2016-03-01 23:12
I respectfully disagree on filtering out anything with the callsign.  I would rather see what the plane is actually broadcasting.  Besides, to parrot some of Mike's comments, I feel the EFB is the "brains", and the place to filter the data as necessary.

**Comment by bkwny** [comment] 2016-03-01 23:12
@Axtel4 - I'm talking about the guy who squits my Mode S on purpose, commits an airspace violation, and then lands.  How would I defend myself against the onslaught of FAA enforcement actions that would no doubt be taken against me?  This whole idea that anybody can put any Mode S code he likes into any squitter and go fly around with it is just beyond ludicrous.

@Nokomis449 - Re: filtering, I agree.  Don't filter, just print what the aircraft sent.

**Comment by skypuppy** [comment] 2016-03-01 23:14
imagine that!  People wanting their privacy.  Why, I never <huff>.

**Comment by Axtel4** [comment] 2016-03-01 23:27
Interesting question.  How does one guard against that?

**Comment by bkwny** [comment] 2016-03-01 23:31
@Axtel4 - One can't.  A syntactically valid squit is just that.  It doesn't matter who sent it or whether the data in it is true.

**Comment by bkwny** [comment] 2016-03-01 23:45
We have public key cryptography but the ADS-B system designers didn't employ it.

**Comment by peepsnet** [comment] 2016-03-02 00:23
The callsigns will have to match because the CPDLC system will fail otherwise. I am an SME for implimenting this at KFLL
https://www.google.com/search?q=cpdlc&oq=cpdlc&aqs=chrome..69i57j0l3.1863j0j4&client=tablet-android-hms-tmobile-us&sourceid=chrome-mobile&ie=UTF-8

**Comment by bkwny** [comment] 2016-03-02 00:30
Squitting does not require talking to a controller.

**Comment by cyoung** [comment] 2016-03-02 00:34
The same problem exists in many different forms - you can call a controller with the call sign of someone else, use the squawk code of someone else, etc. We can only save the world one issue at a time and this issue is outside the scope of #298.

**Comment by Axtel4** [comment] 2016-03-02 00:37
And at a minimum requires VDL Mode 2 which most GA aircraft doesn't have installed.

**Comment by skypuppy** [comment] 2016-03-02 01:03
Thank you, Chris!

**Comment by ScraboTower** [comment] 2016-03-02 04:23
@Ergonomicmike - sorry been away for a few days. I still have the loan of the SkyRadar , Stratux is at 7b1 ... What you want me to check ?

**Comment by cyoung** [comment] 2016-03-02 04:36
There have been some significant changes relevant to 1090 traffic since v0.7b1, @ScraboTower. If you could download http://updates.stratux.me/builds/update-stratux-v0.7b3-d714a5139e.sh and use the "update" feature in the interface it will bring you up to the latest.

**Comment by ScraboTower** [comment] 2016-03-02 04:49
Sorry brain failure.   I am already at 7b3, did it and flew with it on Saturday

**Comment by cyoung** [comment] 2016-03-02 04:52
The release versions will lag behind the "commit" version, like they always did - but now upgrading to the latest commit is easier to do for anyone without recompiling from source. There are 93 "v0.7b3" versions you could have now - check the status page, if it doesn't say "d714a5139e" then it's not the latest.

**Comment by Ergonomicmike** [comment] 2016-03-02 05:00
@ScraboTower Once you have the Stratux updated, we're interested in whether the SkyRadar displays the same goofy call signs we started noticing in the Stratux lately.(See above for examples.) Kind of a sanity check.

**Comment by ScraboTower** [comment] 2016-03-02 23:52
Ran for 5 hours just sitting on office desk but only once noticed any diff - SkyRadar showed the callsign DPJ987 but  Stratux("d714a5139e") didnt - all other data elements matched.

FDX3154 reported 0 altitude on both devices.

**Comment by Ergonomicmike** [comment] 2016-03-03 00:04
Thx. What did Stratux show for the call sign of DPJ987 then? Blanks? Question marks? Dashes? Chris will probably ask for your logs.

**Comment by ScraboTower** [comment] 2016-03-03 00:32
WingX displayed blanks

**Comment by Axtel4** [comment] 2016-03-03 02:45
I captures these 00000000 Flight IDs this evening:
From Statux:
![0000_2](https://cloud.githubusercontent.com/assets/15059010/13483143/96967eca-e0b7-11e5-8f1b-cdca6aa90c99.JPG)

From RTL1090:

![0000_1](https://cloud.githubusercontent.com/assets/15059010/13483141/9210aefc-e0b7-11e5-93c9-c85f4661877a.jpg)

**Comment by jthawkes** [comment] 2016-03-03 03:43
Since the Flight ID can be entered manually why worry about it.

The FAA (and other locations that use the ICAO planning system) use the ICAO hex address to identify aircraft.  
You can also simply decode U.S. ICAO addresses to get the A/C callsign anyway. They use a STD formula to get them. I believe that changing the ICAO address is harder to do.

http://www.faa.gov/about/office_org/headquarters_offices/ato/service_units/air_traffic_services/flight_plan_filing/media/filing_adsb_capability_faa_icao_flight_plan.pdf

**Comment by AvSquirrel** [comment] 2016-03-03 13:01
@Nokomis449 , @bkwny --

>  A syntactically valid squit is just that. It doesn't matter who sent it or whether the data in it is true.

Agreed 100%. Like I said a couple days ago, any valid, checksummed callsign message should be passed. I'm still on the fence on two corner cases.

- Stratux receives a DF=17, TC = 1-4 extended squitter ADS-B identification message that is decoded and passes checksum verification, but contains a callsign with invalid characters. In other words, the emitting transponder intentionally sent characters that it shouldn't have. My inclination is to let it ride, since other receivers should also be seeing the same thing.
- Stratux receives a DF=21 (Comm-B, non-ES / non-ADS-B) that decodes with invalid characters. This format doesn't allow checksum verification by outside observers (the checksum encodes the ICAO ID of the aircraft; radar stations and other Comm-B ground emitters can verify the checksum because they know who they are talking to, but we don't) so dump1090 has to "guess" if the message decoded properly. My inclination is to drop DF21 callsign decoding since an ADS-B target will also send DF17 callsign messages.

![image](https://cloud.githubusercontent.com/assets/14127245/13494914/fe692bce-e10c-11e5-93f5-2cfa3b3b921c.png)

Thoughts?

**Comment by Ergonomicmike** [comment] 2016-03-03 15:03
Don't know if this code was manually entered or is the ICAO coming thru? (In caps instead of lower case?)

![Screenshot](http://s12.postimg.org/salr9wyrh/stratux_traffic_hex.jpg)

**Comment by Axtel4** [comment] 2016-03-03 15:21
Do you have the dump1090 and ES log for that?

**Comment by AvSquirrel** [comment] 2016-03-03 15:46
IIRC, we've always shown the ICAO code (in caps, grayed out) if the callsign isn't available.

Check out @axtel4's screenshot in the first post of #172.

**Comment by Ergonomicmike** [comment] 2016-03-03 15:48
Unfortunately, not for that one. (Did a reminage before installing the jessie kernel, and default is Logs off.)

But I caught another one. A54D73.

https://www.sendspace.com/file/xnk0pa

**Comment by Ergonomicmike** [comment] 2016-03-03 15:52
@AvSquirrel You're correct. Mine is consistent with Axtel4's screenshot from #172. (I searched this issue for similar and didn't see any and so thought it was a new anomaly.) So, NM.

**Comment by Ergonomicmike** [comment] 2016-03-03 17:08
@AvSquirrel Not to over complicate this - I like your idea above for displaying DF 17 & 21 call signs. As a final and/or additional fall back position, if a call sign is questionable (spaces? all 0's? Just an "N"? Can't really test for BWIFATTY) then treat it like it isn't available and display ICAO as you're doing now when a call sign isn't available?

**Comment by Ergonomicmike** [comment] 2016-03-03 17:28
I sound double minded because previously I've suggested that Stratux just display what's sent. I'm still okay w/ that. The potential advantage of displaying ICAO when in doubt is that, unlike 00000000, ICAO call signs should be unique. (In theory.)

**Comment by bkwny** [comment] 2016-03-03 19:42
Can the Web UI display both the ICAO code and the aircraft-operator-provided identifier?  Why is the Web UI built in such a way that it displays the ICAO code inside the colored icon and then switches to the aircraft-operator-provided identifier once Stratux knows same?

**Comment by Ergonomicmike** [comment] 2016-03-03 21:09
I wonder if all EFB's simply repeat what they're sent w.r.t. Call Signs? (But that's out of our control.)

**Comment by Ergonomicmike** [comment] 2016-03-03 21:14
Just caught an ICAO Stratux call sign. iFly reports "Unknown." (And then it changed to a UAL flight when Stratux caught up.)

**Comment by Axtel4** [comment] 2016-03-03 21:16
DroidEFB and Avare don't repeat any call signs.

**Comment by Ergonomicmike** [comment] 2016-03-03 21:24
IFly will repeat the small "e" when the message type option is enabled in the Stratux Settings page. So I thought it repeated everything sent to it. Does Stratux send ICAO only call signs to the EFB?

**Comment by Ergonomicmike** [comment] 2016-03-03 21:46
Off topic, but I thought it was a silly gimmick when iFly started showing Call Signs. But it's kinda cool in the pattern - I can tell who the tower is talking to for sequencing.

**Comment by ScraboTower** [comment] 2016-03-05 02:17
WingX already displayed the call sign and Hilton recently added an option to switch it on/off... I thought at times it cluttered the screen a lot, particularly on smaller screens like an iPhone

**Comment by Ergonomicmike** [comment] 2016-03-05 02:23
I'm off topic again, but iFly only shows them when you're zoomed in a lot. (That is, no clutter in cruise.)

**Comment by ScraboTower** [comment] 2016-03-05 02:32
>> I'm off topic again, but iFly only shows them when you're zoomed in a lot. (That is, no clutter in cruise.)

That's a good idea.

**Comment by cyoung** [comment] 2016-03-05 04:05
So I built a 1090 "transmitter" that sends specific messages "over the air" (closed loop in this case) and fed in `*8dc02d2122c30c30c30c30deacc6;` to older versions of the software - dump1090-antirez, dump1090-MalcolmRobb, and the current version. All of them produce a target with identifier '00000000'.

Have you seen this happen again?

@bkwny - was not able to pull data from your logs, all of them were blank after decompressing. Do you have 'Record Logs' on?

**Comment by bkwny** [comment] 2016-03-05 17:51
@cyoung - Didn't then, do now.

**Comment by cyoung** [comment] 2016-03-05 22:23
How often do they show up? I'm not able to reproduce it locally.

**Comment by Ergonomicmike** [comment] 2016-03-05 23:55
If you're asking about 00000000's,  they seem "random" to me, in the sense that I can't predict them. I just upgraded to 18de alpha and will let it run for the evening. If I find any 00000000's in a log, I'll let you know.

**Comment by Ergonomicmike** [comment] 2016-03-06 00:07
@cyoung There's no 58c6.sh in the /builds directory. Is it in process?

**Comment by Ergonomicmike** [comment] 2016-03-06 00:39
-

**Comment by cyoung** [comment] 2016-03-06 00:43
Where do you get 58c6?

17ab2e5c41 is the latest, it's there now. See right hand side on the commits list to verify latest builds: https://github.com/cyoung/stratux/commits/master


How often are you seeing the "00000000" identifiers? Trying to figure out how long I need to have my setup running before I see one.

**Comment by Ergonomicmike** [comment] 2016-03-06 00:51
I get 58c6 (the last 4 digits of the .sh file) in https://github.com/cyoung/stratux/releases.

So far I haven't seen any 00000000's this afternoon. (Saw a 33 go into PHX.) It's a slow Satuday here in Phx. Not very many air carriers flying. Am recording a log and will check it later tonight.

**Comment by cyoung** [comment] 2016-03-08 00:34
Not able to reproduce now. I don't think it was an issue on our end. The changes will go to a release version and if there's a widespread issue we'll surely hear about it and reopen.

**Closed by cyoung** 2016-03-08 00:34 UTC
Labels: bug
